<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Authentication\**" />
    <Compile Remove="Email\**" />
    <Compile Remove="FileStorage\**" />
    <Compile Remove="Hashing\**" />
    <Compile Remove="Time\**" />
    <EmbeddedResource Remove="Authentication\**" />
    <EmbeddedResource Remove="Email\**" />
    <EmbeddedResource Remove="FileStorage\**" />
    <EmbeddedResource Remove="Hashing\**" />
    <EmbeddedResource Remove="Time\**" />
    <None Remove="Authentication\**" />
    <None Remove="Email\**" />
    <None Remove="FileStorage\**" />
    <None Remove="Hashing\**" />
    <None Remove="Time\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ValenceHub.Application\ValenceHub.Application.csproj" />
    <ProjectReference Include="..\ValenceHub.Domain\ValenceHub.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
