<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ValenceHub.Application\ValenceHub.Application.csproj" />
    <ProjectReference Include="..\ValenceHub.Domain\ValenceHub.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Authentication\" />
    <Folder Include="Email\" />
    <Folder Include="Hashing\" />
    <Folder Include="FileStorage\" />
    <Folder Include="Time\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
