<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Common\**" />
    <Compile Remove="Write\Contexts\ValenceHubWriteDbContext.cs\**" />
    <EmbeddedResource Remove="Common\**" />
    <EmbeddedResource Remove="Write\Contexts\ValenceHubWriteDbContext.cs\**" />
    <None Remove="Common\**" />
    <None Remove="Write\Contexts\ValenceHubWriteDbContext.cs\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ValenceHub.Application\ValenceHub.Application.csproj" />
    <ProjectReference Include="..\ValenceHub.Domain\ValenceHub.Domain.csproj" />
    <ProjectReference Include="..\ValenceHub.Infrastructure\ValenceHub.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Read\Idempotency\" />
    <Folder Include="Write\Migrations\" />
  </ItemGroup>

</Project>
