<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ValenceHub.Application\ValenceHub.Application.csproj" />
    <ProjectReference Include="..\ValenceHub.Domain\ValenceHub.Domain.csproj" />
  </ItemGroup>

</Project>
