<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Features\**" />
    <Compile Remove="ReadModels\**" />
    <Compile Remove="Validators\**" />
    <EmbeddedResource Remove="Features\**" />
    <EmbeddedResource Remove="ReadModels\**" />
    <EmbeddedResource Remove="Validators\**" />
    <None Remove="Features\**" />
    <None Remove="ReadModels\**" />
    <None Remove="Validators\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ValenceHub.Domain\ValenceHub.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="MediatR" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions\Services\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
