<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entities\**" />
    <Compile Remove="Enums\**" />
    <Compile Remove="Exceptions\**" />
    <Compile Remove="ValueObjects\**" />
    <EmbeddedResource Remove="Entities\**" />
    <EmbeddedResource Remove="Enums\**" />
    <EmbeddedResource Remove="Exceptions\**" />
    <EmbeddedResource Remove="ValueObjects\**" />
    <None Remove="Entities\**" />
    <None Remove="Enums\**" />
    <None Remove="Exceptions\**" />
    <None Remove="ValueObjects\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Primitives\" />
  </ItemGroup>

</Project>
